### ISSUE TITLE
today's change upsets extension

### ISSUE THREAD

**Issue by atomicthumbs** [bucketfishy/cohost-better-notifications#1]
the cohost staff made it so you can middle click on notifications. now the extension kinda works but only halfway. doesn't seem like it'll take all that much work

[also your discord's set to friends only, unless i'm using it wrong, hence a github issue instead]

**Comment by bucketfish** [comment]
oh man, thank you!

i don't think there's a way to set discord to not-friends-only? aha. unfortunate

**Comment by sharkaccino** [comment]
@bucketfishy maybe you turned this off?

![image](https://user-images.githubusercontent.com/31686191/204075885-99dd3f59-5fc9-44ca-a3ec-67403815f0a1.png)
